package cppfm.transform;

import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Process-wide transformed-method marker shared by generated bytecode and
 * the native/manual hook shell.
 *
 * <p>A manual shadow hook must guard its legacy callback like this:</p>
 * <pre>
 * if (!MixinDispatch.isManualHookSuppressed("net/foo/Target", "tick", "()V")) {
 *     // legacy MixinHooks invocation
 * }
 * </pre>
 *
 * <p>The transformer calls {@link #markTransformed(String, String, String)}
 * once when a method's bytecode is changed.  This makes the generated
 * bytecode the unique execution path and prevents a later manual hook from
 * invoking the same handler twice.  The API contains no dependency on the
 * existing bridge, so it can be used by a future MixinHooks integration
 * without a class-loader cycle.</p>
 */
public final class MixinDispatch {
    private static final Set<String> TRANSFORMED = ConcurrentHashMap.newKeySet();
    private static final ThreadLocal<Set<String>> ACTIVE = ThreadLocal.withInitial(LinkedHashSet::new);

    private MixinDispatch() { }

    public static void markTransformed(String owner, String name, String descriptor) {
        TRANSFORMED.add(key(owner, name, descriptor));
    }

    public static void unmarkTransformed(String owner, String name, String descriptor) {
        TRANSFORMED.remove(key(owner, name, descriptor));
    }

    public static boolean isTransformed(String owner, String name, String descriptor) {
        return TRANSFORMED.contains(key(owner, name, descriptor));
    }

    /** Alias intended for manual-hook guards. */
    public static boolean isManualHookSuppressed(String owner, String name, String descriptor) {
        return isTransformed(owner, name, descriptor);
    }

    /** Register a dynamic invocation scope for diagnostics and re-entry guards. */
    public static Scope enter(String owner, String name, String descriptor) {
        String key = key(owner, name, descriptor);
        ACTIVE.get().add(key);
        return new Scope(key);
    }

    public static boolean isActive(String owner, String name, String descriptor) {
        return ACTIVE.get().contains(key(owner, name, descriptor));
    }

    public static Set<String> transformedMethods() {
        return Collections.unmodifiableSet(new LinkedHashSet<>(TRANSFORMED));
    }

    public static void clear() {
        TRANSFORMED.clear();
        ACTIVE.remove();
    }

    private static String key(String owner, String name, String descriptor) {
        return owner.replace('.', '/') + "#" + name + descriptor;
    }

    /** AutoCloseable scope for generated dispatchers and launcher diagnostics. */
    public static final class Scope implements AutoCloseable {
        private final String key;
        private boolean closed;

        private Scope(String key) { this.key = key; }

        @Override public void close() {
            if (!closed) {
                ACTIVE.get().remove(key);
                closed = true;
            }
        }
    }
}
