package cppfm.transform;

import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Process-wide transformed-method marker shared by generated bytecode and
 * the native/manual hook shell.
 *
 * <p>A manual shadow hook must guard its legacy callback like this:</p>
 * <pre>
 * if (!MixinDispatch.isManualHookSuppressed("net/foo/Target", "tick", "()V")) {
 *     // legacy MixinHooks invocation
 * }
 * </pre>
 *
 * <p>The transformer calls {@link #markTransformed(String, String, String)}
 * once when a method's bytecode is changed.  This makes the generated
 * bytecode the unique execution path and prevents a later manual hook from
 * invoking the same handler twice.  The API contains no dependency on the
 * existing bridge, so it can be used by a future MixinHooks integration
 * without a class-loader cycle.</p>
 */
public final class MixinDispatch {
    private static final Set<String> TRANSFORMED = ConcurrentHashMap.newKeySet();
    private static final ThreadLocal<Set<String>> ACTIVE = ThreadLocal.withInitial(LinkedHashSet::new);

    private MixinDispatch() { }

    public static void markTransformed(String owner, String name, String descriptor) {
        TRANSFORMED.add(key(owner, name, descriptor));
    }

    public static void unmarkTransformed(String owner, String name, String descriptor) {
        TRANSFORMED.remove(key(owner, name, descriptor));
    }

    public static boolean isTransformed(String owner, String name, String descriptor) {
        return TRANSFORMED.contains(key(owner, name, descriptor));
    }

    /**
     * Check the method-level marker when a legacy/manual hook does not carry
     * a JVM descriptor.  Shadow source helpers commonly expose only
     * {@code (target, method, value, args...)}, so an exact descriptor cannot
     * be reconstructed reliably from a null return value.  The generated
     * transformer marks all overloads it owns; this name-level check is used
     * only by those legacy helpers to avoid dispatching the same handler a
     * second time.
     */
    public static boolean isAnyTransformed(String owner, String name) {
        String prefix = owner.replace('.', '/') + "#" + name;
        for (String marker : TRANSFORMED) if (marker.startsWith(prefix)) return true;
        return false;
    }

    /** Alias intended for manual-hook guards. */
    public static boolean isManualHookSuppressed(String owner, String name, String descriptor) {
        return isTransformed(owner, name, descriptor);
    }

    /** Register a dynamic invocation scope for diagnostics and re-entry guards. */
    public static Scope enter(String owner, String name, String descriptor) {
        String key = key(owner, name, descriptor);
        ACTIVE.get().add(key);
        return new Scope(key);
    }

    public static boolean isActive(String owner, String name, String descriptor) {
        return ACTIVE.get().contains(key(owner, name, descriptor));
    }

    public static Set<String> transformedMethods() {
        return Collections.unmodifiableSet(new LinkedHashSet<>(TRANSFORMED));
    }

    /**
     * Restore the transformed-method ledger to a pre-transform checkpoint.
     *
     * <p>A class-file transform is transactional from the loader's point of
     * view: if bytecode validation fails, the original bytes are returned.
     * The ledger must obey the same rule or the manual compatibility hooks
     * would be suppressed even though no transformed bytes were defined.</p>
     */
    public static void rollbackTo(Set<String> checkpoint) {
        if (checkpoint == null) {
            TRANSFORMED.clear();
            return;
        }
        TRANSFORMED.removeIf(marker -> !checkpoint.contains(marker));
    }

    public static void clear() {
        TRANSFORMED.clear();
        ACTIVE.remove();
    }

    private static String key(String owner, String name, String descriptor) {
        return owner.replace('.', '/') + "#" + name + descriptor;
    }

    /** AutoCloseable scope for generated dispatchers and launcher diagnostics. */
    public static final class Scope implements AutoCloseable {
        private final String key;
        private boolean closed;

        private Scope(String key) { this.key = key; }

        @Override public void close() {
            if (!closed) {
                ACTIVE.get().remove(key);
                closed = true;
            }
        }
    }
}
