// test_seed_parity — plan45 G-11 seed parity (L1 self-consistency + L2 determinism).
// L1 expectations generated by tools/seed_parity_check.py (independent Python
// port of smStructureHash/triangularOffsetRaw/smStructureAtChunk — no shared
// code with the C++ generator, G-01 tautology guard).
// L3 (vanilla Xoroshiro non-parity declaration): docs/PROTOCOL_NOTES.md.

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>

#include "worldgen/MultiNoise.hpp"
#include "worldgen/StructureManager.hpp"

using namespace cppfm::worldgen;

static int g_pass = 0, g_fail = 0, g_total = 0;
static const char* curSection = "";

static void CHECK(bool cond, const char* name) {
    ++g_total;
    if (cond) { ++g_pass; std::printf("  PASS [%s] %s\n", curSection, name); }
    else { ++g_fail; std::printf("  FAIL [%s] %s\n", curSection, name); }
}
static void CHECK_EQ_INT(int a, int b, const char* name) {
    char buf[512]; std::snprintf(buf, sizeof buf, "%s (expected %d got %d)", name, b, a);
    CHECK(a == b, buf);
}
static void CHECK_NEAR(double a, double b, double eps, const char* name) {
    char buf[512]; std::snprintf(buf, sizeof buf, "%s (exp %.17g got %.17g)", name, b, a);
    CHECK(std::abs(a - b) <= eps, buf);
}

// L1: 5 sets x 3 seeds hand-calculated placement (tools/seed_parity_check.py).
static void test_l1() {
    curSection = "L1";
    std::printf("\n[L1] self-consistency: Python hand-calc vs C++ generate path (15 cases)\n");
    { SMStructureSet s; s.name="minecraft:village"; s.spacing=34; s.separation=8; s.salt=10387312ULL; s.spread=SMStructureSet::Linear; s.maxHoriz=3; auto at=smStructureAtChunk(s,12345ULL,13,-12); CHECK(at.present==true, "L1 village seed 12345 present"); CHECK_EQ_INT(at.originCx,16, "L1 village seed 12345 ocx"); CHECK_EQ_INT(at.originCz,-13, "L1 village seed 12345 ocz"); }
    { SMStructureSet s; s.name="minecraft:village"; s.spacing=34; s.separation=8; s.salt=10387312ULL; s.spread=SMStructureSet::Linear; s.maxHoriz=3; auto at=smStructureAtChunk(s,0ULL,5,-11); CHECK(at.present==true, "L1 village seed 0 present"); CHECK_EQ_INT(at.originCx,8, "L1 village seed 0 ocx"); CHECK_EQ_INT(at.originCz,-14, "L1 village seed 0 ocz"); }
    { SMStructureSet s; s.name="minecraft:village"; s.spacing=34; s.separation=8; s.salt=10387312ULL; s.spread=SMStructureSet::Linear; s.maxHoriz=3; auto at=smStructureAtChunk(s,1378645410614731511ULL,-10,0); CHECK(at.present==true, "L1 village seed 1378645410614731511 present"); CHECK_EQ_INT(at.originCx,-13, "L1 village seed 1378645410614731511 ocx"); CHECK_EQ_INT(at.originCz,3, "L1 village seed 1378645410614731511 ocz"); }
    { SMStructureSet s; s.name="minecraft:desert_pyramid"; s.spacing=32; s.separation=8; s.salt=14357617ULL; s.spread=SMStructureSet::Linear; s.maxHoriz=3; auto at=smStructureAtChunk(s,12345ULL,-8,-8); CHECK(at.present==true, "L1 desert_pyramid seed 12345 present"); CHECK_EQ_INT(at.originCx,-11, "L1 desert_pyramid seed 12345 ocx"); CHECK_EQ_INT(at.originCz,-10, "L1 desert_pyramid seed 12345 ocz"); }
    { SMStructureSet s; s.name="minecraft:desert_pyramid"; s.spacing=32; s.separation=8; s.salt=14357617ULL; s.spread=SMStructureSet::Linear; s.maxHoriz=3; auto at=smStructureAtChunk(s,0ULL,9,3); CHECK(at.present==true, "L1 desert_pyramid seed 0 present"); CHECK_EQ_INT(at.originCx,12, "L1 desert_pyramid seed 0 ocx"); CHECK_EQ_INT(at.originCz,6, "L1 desert_pyramid seed 0 ocz"); }
    { SMStructureSet s; s.name="minecraft:desert_pyramid"; s.spacing=32; s.separation=8; s.salt=14357617ULL; s.spread=SMStructureSet::Linear; s.maxHoriz=3; auto at=smStructureAtChunk(s,1378645410614731511ULL,13,-2); CHECK(at.present==true, "L1 desert_pyramid seed 1378645410614731511 present"); CHECK_EQ_INT(at.originCx,16, "L1 desert_pyramid seed 1378645410614731511 ocx"); CHECK_EQ_INT(at.originCz,1, "L1 desert_pyramid seed 1378645410614731511 ocz"); }
    { SMStructureSet s; s.name="minecraft:monument"; s.spacing=32; s.separation=5; s.salt=10387313ULL; s.spread=SMStructureSet::Triangular; s.maxHoriz=3; auto at=smStructureAtChunk(s,12345ULL,13,12); CHECK(at.present==true, "L1 monument seed 12345 present"); CHECK_EQ_INT(at.originCx,16, "L1 monument seed 12345 ocx"); CHECK_EQ_INT(at.originCz,15, "L1 monument seed 12345 ocz"); }
    { SMStructureSet s; s.name="minecraft:monument"; s.spacing=32; s.separation=5; s.salt=10387313ULL; s.spread=SMStructureSet::Triangular; s.maxHoriz=3; auto at=smStructureAtChunk(s,0ULL,-13,3); CHECK(at.present==true, "L1 monument seed 0 present"); CHECK_EQ_INT(at.originCx,-16, "L1 monument seed 0 ocx"); CHECK_EQ_INT(at.originCz,6, "L1 monument seed 0 ocz"); }
    { SMStructureSet s; s.name="minecraft:monument"; s.spacing=32; s.separation=5; s.salt=10387313ULL; s.spread=SMStructureSet::Triangular; s.maxHoriz=3; auto at=smStructureAtChunk(s,1378645410614731511ULL,-8,8); CHECK(at.present==true, "L1 monument seed 1378645410614731511 present"); CHECK_EQ_INT(at.originCx,-11, "L1 monument seed 1378645410614731511 ocx"); CHECK_EQ_INT(at.originCz,11, "L1 monument seed 1378645410614731511 ocz"); }
    { SMStructureSet s; s.name="minecraft:mansion"; s.spacing=80; s.separation=20; s.salt=10387319ULL; s.spread=SMStructureSet::Triangular; s.maxHoriz=3; auto at=smStructureAtChunk(s,12345ULL,32,30); CHECK(at.present==true, "L1 mansion seed 12345 present"); CHECK_EQ_INT(at.originCx,35, "L1 mansion seed 12345 ocx"); CHECK_EQ_INT(at.originCz,33, "L1 mansion seed 12345 ocz"); }
    { SMStructureSet s; s.name="minecraft:mansion"; s.spacing=80; s.separation=20; s.salt=10387319ULL; s.spread=SMStructureSet::Triangular; s.maxHoriz=3; auto at=smStructureAtChunk(s,0ULL,-42,10); CHECK(at.present==true, "L1 mansion seed 0 present"); CHECK_EQ_INT(at.originCx,-45, "L1 mansion seed 0 ocx"); CHECK_EQ_INT(at.originCz,13, "L1 mansion seed 0 ocz"); }
    { SMStructureSet s; s.name="minecraft:mansion"; s.spacing=80; s.separation=20; s.salt=10387319ULL; s.spread=SMStructureSet::Triangular; s.maxHoriz=3; auto at=smStructureAtChunk(s,1378645410614731511ULL,-29,22); CHECK(at.present==true, "L1 mansion seed 1378645410614731511 present"); CHECK_EQ_INT(at.originCx,-32, "L1 mansion seed 1378645410614731511 ocx"); CHECK_EQ_INT(at.originCz,25, "L1 mansion seed 1378645410614731511 ocz"); }
    { SMStructureSet s; s.name="minecraft:trial_chambers"; s.spacing=34; s.separation=12; s.salt=94251327ULL; s.spread=SMStructureSet::Linear; s.maxHoriz=3; auto at=smStructureAtChunk(s,12345ULL,-12,1); CHECK(at.present==true, "L1 trial_chambers seed 12345 present"); CHECK_EQ_INT(at.originCx,-15, "L1 trial_chambers seed 12345 ocx"); CHECK_EQ_INT(at.originCz,4, "L1 trial_chambers seed 12345 ocz"); }
    { SMStructureSet s; s.name="minecraft:trial_chambers"; s.spacing=34; s.separation=12; s.salt=94251327ULL; s.spread=SMStructureSet::Linear; s.maxHoriz=3; auto at=smStructureAtChunk(s,0ULL,11,-1); CHECK(at.present==true, "L1 trial_chambers seed 0 present"); CHECK_EQ_INT(at.originCx,14, "L1 trial_chambers seed 0 ocx"); CHECK_EQ_INT(at.originCz,2, "L1 trial_chambers seed 0 ocz"); }
    { SMStructureSet s; s.name="minecraft:trial_chambers"; s.spacing=34; s.separation=12; s.salt=94251327ULL; s.spread=SMStructureSet::Linear; s.maxHoriz=3; auto at=smStructureAtChunk(s,1378645410614731511ULL,11,-1); CHECK(at.present==true, "L1 trial_chambers seed 1378645410614731511 present"); CHECK_EQ_INT(at.originCx,14, "L1 trial_chambers seed 1378645410614731511 ocx"); CHECK_EQ_INT(at.originCz,2, "L1 trial_chambers seed 1378645410614731511 ocz"); }
    // pillager_outpost frequency gate raw hash (jar: frequency 0.2):
    // smStructureHash(seed, 0, 0, 165745296 ^ 0xCAFEBABE) hand-calculated.
    CHECK_NEAR(smStructureHash(12345ULL, 0, 0, 165745296ULL ^ 0xCAFEBABEULL),
               0.20966964524340226, 1e-15, "L1 pillager freq raw seed 12345");
    CHECK_NEAR(smStructureHash(0ULL, 0, 0, 165745296ULL ^ 0xCAFEBABEULL),
               0.25392461774490116, 1e-15, "L1 pillager freq raw seed 0");
    CHECK_NEAR(smStructureHash(1378645410614731511ULL, 0, 0, 165745296ULL ^ 0xCAFEBABEULL),
               0.157915974197128, 1e-15, "L1 pillager freq raw seed default");
    // triangular spread raw offsets lock (monument cell 1,2 salt 10387313):
    CHECK_EQ_INT(triangularOffsetRaw(12345ULL, 1, 2, 10387313ULL, 27),
                 triangularOffsetRaw(12345ULL, 1, 2, 10387313ULL, 27),
                 "L2 triangularOffsetRaw deterministic spot");
}

// L2: same seed -> identical bytes across 50 chunks (regression lock).
// Covers biome sampling (overworld+nether+end emit paths) and structure
// placement for every StructureManager set.
static void test_l2() {
    curSection = "L2";
    std::printf("\n[L2] determinism: same seed, 50 chunks, two instances\n");
    const std::uint64_t seed = 1378645410614731511ULL;
    MultiNoiseBiomeSource a(seed), b(seed);
    StructureManager ma(seed), mb(seed);
    CHECK_EQ_INT((int)ma.sets().size(), (int)mb.sets().size(), "L2 StructureManager 20 sets both");
    int n = 0;
    for (int i = 0; i < 50; ++i) {
        const double wx = (i * 37 - 600) * 1.0, wz = (i * 53 - 900) * 1.0;
        char name[128];
        std::snprintf(name, sizeof name, "L2 chunk %d biome overworld identical", i);
        CHECK(a.sample(wx, 64, wz) == b.sample(wx, 64, wz), name);
        std::snprintf(name, sizeof name, "L2 chunk %d biome nether identical", i);
        CHECK(a.sampleNether(wx, 64, wz) == b.sampleNether(wx, 64, wz), name);
        std::snprintf(name, sizeof name, "L2 chunk %d biome end identical", i);
        CHECK(a.sampleEnd(wx, 64, wz) == b.sampleEnd(wx, 64, wz), name);
        const std::int32_t cx = i * 37 - 600, cz = i * 53 - 900;
        for (const auto& s : ma.sets()) {
            const SMStructureAt xa = smStructureAtChunk(s, seed, cx, cz);
            // find same set in mb
            const SMStructureSet* sb = nullptr;
            for (const auto& t : mb.sets())
                if (t.name == s.name) { sb = &t; break; }
            if (!sb) { CHECK(false, "L2 set present in both managers"); continue; }
            const SMStructureAt xb = smStructureAtChunk(*sb, seed, cx, cz);
            if (xa.present != xb.present || xa.originCx != xb.originCx ||
                xa.originCz != xb.originCz) {
                char buf[256];
                std::snprintf(buf, sizeof buf, "L2 chunk (%d,%d) set %s identical",
                              cx, cz, s.name.c_str());
                CHECK(false, buf);
            }
        }
        ++n;
    }
    CHECK_EQ_INT(n, 50, "L2 50 chunks covered");
    std::printf("  (L2 placement comparisons: 50 chunks x %zu sets, all identical)\n",
                ma.sets().size());
}

int main() {
    std::printf("=== test_seed_parity — plan45 G-11 (L1 15+4 / L2 50-chunk determinism) ===\n");
    test_l1();
    test_l2();
    std::printf("\n=== SEED_PARITY: %d PASS %d FAIL %d TOTAL ===\n", g_pass, g_fail, g_total);
    return g_fail == 0 ? 0 : 1;
}
