package net.minecraft.entity;

public enum SpawnReason { NATURAL, CHUNK_GENERATION, SPAWNER, STRUCTURE, BREEDING, MOB_SUMMONED, JOCKEY, EVENT, CONVERSION, REINFORCEMENT, TRIGGERED, BUCKET, DISPENSER, PATROL, COMMAND, DEFAULT }
