package net.fabricmc.fabric.api.tag.convention.v2;

import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.tag.TagKey;
import net.minecraft.util.Identifier;
import net.minecraft.block.Block;

/** Generated from the Fabric v2 convention-tags 1.21.4 public catalog. */
public final class ConventionalBlockTags {
    private ConventionalBlockTags() { }

    private static TagKey<Block> register(String path) {
        return TagKey.of(RegistryKeys.BLOCK, Identifier.of("c", path));
    }

    public static final TagKey<Block> STONES = register("stones");
    public static final TagKey<Block> COBBLESTONES = register("cobblestones");
    public static final TagKey<Block> DEEPSLATE_COBBLESTONES = register("cobblestones/deepslate");
    public static final TagKey<Block> INFESTED_COBBLESTONES = register("cobblestones/infested");
    public static final TagKey<Block> MOSSY_COBBLESTONES = register("cobblestones/mossy");
    public static final TagKey<Block> NORMAL_COBBLESTONES = register("cobblestones/normal");
    public static final TagKey<Block> NETHERRACKS = register("netherracks");
    public static final TagKey<Block> END_STONES = register("end_stones");
    public static final TagKey<Block> GRAVELS = register("gravels");
    public static final TagKey<Block> OBSIDIANS = register("obsidians");
    public static final TagKey<Block> NORMAL_OBSIDIANS = register("obsidians/normal");
    public static final TagKey<Block> CRYING_OBSIDIANS = register("obsidians/crying");
    public static final TagKey<Block> ORES = register("ores");
    public static final TagKey<Block> COAL_ORES = register("ores/coal");
    public static final TagKey<Block> COPPER_ORES = register("ores/copper");
    public static final TagKey<Block> DIAMOND_ORES = register("ores/diamond");
    public static final TagKey<Block> EMERALD_ORES = register("ores/emerald");
    public static final TagKey<Block> GOLD_ORES = register("ores/gold");
    public static final TagKey<Block> IRON_ORES = register("ores/iron");
    public static final TagKey<Block> LAPIS_ORES = register("ores/lapis");
    public static final TagKey<Block> NETHERITE_SCRAP_ORES = register("ores/netherite_scrap");
    public static final TagKey<Block> QUARTZ_ORES = register("ores/quartz");
    public static final TagKey<Block> REDSTONE_ORES = register("ores/redstone");
    public static final TagKey<Block> BARRELS = register("barrels");
    public static final TagKey<Block> WOODEN_BARRELS = register("barrels/wooden");
    public static final TagKey<Block> BOOKSHELVES = register("bookshelves");
    public static final TagKey<Block> CHESTS = register("chests");
    public static final TagKey<Block> WOODEN_CHESTS = register("wooden_chests");
    public static final TagKey<Block> TRAPPED_CHESTS = register("trapped_chests");
    public static final TagKey<Block> ENDER_CHESTS = register("ender_chests");
    public static final TagKey<Block> GLASS_BLOCKS = register("glass_blocks");
    public static final TagKey<Block> GLASS_BLOCKS_COLORLESS = register("glass_blocks_colorless");
    public static final TagKey<Block> GLASS_BLOCKS_CHEAP = register("glass_blocks_cheap");
    public static final TagKey<Block> GLASS_BLOCKS_TINTED = register("glass_blocks_tinted");
    public static final TagKey<Block> GLASS_PANES = register("glass_panes");
    public static final TagKey<Block> GLASS_PANES_COLORLESS = register("glass_panes_colorless");
    public static final TagKey<Block> GLAZED_TERRACOTTAS = register("glazed_terracottas");
    public static final TagKey<Block> CONCRETES = register("concretes");
    public static final TagKey<Block> BUDDING_BLOCKS = register("budding_blocks");
    public static final TagKey<Block> BUDS = register("buds");
    public static final TagKey<Block> CLUSTERS = register("clusters");
    public static final TagKey<Block> VILLAGER_JOB_SITES = register("villager_job_sites");
    public static final TagKey<Block> SANDS = register("sands");
    public static final TagKey<Block> RED_SANDS = register("red_sands");
    public static final TagKey<Block> COLORLESS_SANDS = register("colorless_sands");
    public static final TagKey<Block> SMALL_FLOWERS = register("small_flowers");
    public static final TagKey<Block> TALL_FLOWERS = register("tall_flowers");
    public static final TagKey<Block> FLOWERS = register("flowers");
    public static final TagKey<Block> SANDSTONE_BLOCKS = register("sandstone_blocks");
    public static final TagKey<Block> SANDSTONE_SLABS = register("sandstone_slabs");
    public static final TagKey<Block> SANDSTONE_STAIRS = register("sandstone_stairs");
    public static final TagKey<Block> RED_SANDSTONE_BLOCKS = register("red_sandstone_blocks");
    public static final TagKey<Block> RED_SANDSTONE_SLABS = register("red_sandstone_slabs");
    public static final TagKey<Block> RED_SANDSTONE_STAIRS = register("red_sandstone_stairs");
    public static final TagKey<Block> UNCOLORED_SANDSTONE_BLOCKS = register("uncolored_sandstone_blocks");
    public static final TagKey<Block> UNCOLORED_SANDSTONE_SLABS = register("uncolored_sandstone_slabs");
    public static final TagKey<Block> UNCOLORED_SANDSTONE_STAIRS = register("uncolored_sandstone_stairs");
    public static final TagKey<Block> FENCES = register("fences");
    public static final TagKey<Block> WOODEN_FENCES = register("wooden_fences");
    public static final TagKey<Block> NETHER_BRICK_FENCES = register("nether_brick_fences");
    public static final TagKey<Block> FENCE_GATES = register("fence_gates");
    public static final TagKey<Block> WOODEN_FENCE_GATES = register("wooden_fence_gates");
    public static final TagKey<Block> PUMPKINS = register("pumpkins");
    public static final TagKey<Block> NORMAL_PUMPKINS = register("normal_pumpkins");
    public static final TagKey<Block> CARVED_PUMPKINS = register("carved_pumpkins");
    public static final TagKey<Block> JACK_O_LANTERNS_PUMPKINS = register("jack_o_lanterns_pumpkins");
    public static final TagKey<Block> DYED = register("dyed");
    public static final TagKey<Block> BLACK_DYED = register("black_dyed");
    public static final TagKey<Block> BLUE_DYED = register("blue_dyed");
    public static final TagKey<Block> BROWN_DYED = register("brown_dyed");
    public static final TagKey<Block> CYAN_DYED = register("cyan_dyed");
    public static final TagKey<Block> GRAY_DYED = register("gray_dyed");
    public static final TagKey<Block> GREEN_DYED = register("green_dyed");
    public static final TagKey<Block> LIGHT_BLUE_DYED = register("light_blue_dyed");
    public static final TagKey<Block> LIGHT_GRAY_DYED = register("light_gray_dyed");
    public static final TagKey<Block> LIME_DYED = register("lime_dyed");
    public static final TagKey<Block> MAGENTA_DYED = register("magenta_dyed");
    public static final TagKey<Block> ORANGE_DYED = register("orange_dyed");
    public static final TagKey<Block> PINK_DYED = register("pink_dyed");
    public static final TagKey<Block> PURPLE_DYED = register("purple_dyed");
    public static final TagKey<Block> RED_DYED = register("red_dyed");
    public static final TagKey<Block> WHITE_DYED = register("white_dyed");
    public static final TagKey<Block> YELLOW_DYED = register("yellow_dyed");
    public static final TagKey<Block> STORAGE_BLOCKS = register("storage_blocks");
    public static final TagKey<Block> STORAGE_BLOCKS_BONE_MEAL = register("storage_blocks_bone_meal");
    public static final TagKey<Block> STORAGE_BLOCKS_COAL = register("storage_blocks_coal");
    public static final TagKey<Block> STORAGE_BLOCKS_COPPER = register("storage_blocks_copper");
    public static final TagKey<Block> STORAGE_BLOCKS_DIAMOND = register("storage_blocks_diamond");
    public static final TagKey<Block> STORAGE_BLOCKS_DRIED_KELP = register("storage_blocks_dried_kelp");
    public static final TagKey<Block> STORAGE_BLOCKS_EMERALD = register("storage_blocks_emerald");
    public static final TagKey<Block> STORAGE_BLOCKS_GOLD = register("storage_blocks_gold");
    public static final TagKey<Block> STORAGE_BLOCKS_IRON = register("storage_blocks_iron");
    public static final TagKey<Block> STORAGE_BLOCKS_LAPIS = register("storage_blocks_lapis");
    public static final TagKey<Block> STORAGE_BLOCKS_NETHERITE = register("storage_blocks_netherite");
    public static final TagKey<Block> STORAGE_BLOCKS_RAW_COPPER = register("storage_blocks_raw_copper");
    public static final TagKey<Block> STORAGE_BLOCKS_RAW_GOLD = register("storage_blocks_raw_gold");
    public static final TagKey<Block> STORAGE_BLOCKS_RAW_IRON = register("storage_blocks_raw_iron");
    public static final TagKey<Block> STORAGE_BLOCKS_REDSTONE = register("storage_blocks_redstone");
    public static final TagKey<Block> STORAGE_BLOCKS_RESIN = register("storage_blocks_resin");
    public static final TagKey<Block> STORAGE_BLOCKS_SLIME = register("storage_blocks_slime");
    public static final TagKey<Block> STORAGE_BLOCKS_WHEAT = register("storage_blocks_wheat");
    public static final TagKey<Block> STRIPPED_LOGS = register("stripped_logs");
    public static final TagKey<Block> STRIPPED_WOODS = register("stripped_woods");
    public static final TagKey<Block> PLAYER_WORKSTATIONS_CRAFTING_TABLES = register("player_workstations_crafting_tables");
    public static final TagKey<Block> PLAYER_WORKSTATIONS_FURNACES = register("player_workstations_furnaces");
    public static final TagKey<Block> RELOCATION_NOT_SUPPORTED = register("relocation_not_supported");
    public static final TagKey<Block> SKULLS = register("skulls");
    public static final TagKey<Block> ROPES = register("ropes");
    public static final TagKey<Block> CHAINS = register("chains");
    public static final TagKey<Block> HIDDEN_FROM_RECIPE_VIEWERS = register("hidden_from_recipe_viewers");
    public static final TagKey<Block> ORE_BEARING_GROUND_DEEPSLATE = register("ore_bearing_ground_deepslate");
    public static final TagKey<Block> ORE_BEARING_GROUND_NETHERRACK = register("ore_bearing_ground_netherrack");
    public static final TagKey<Block> ORE_BEARING_GROUND_STONE = register("ore_bearing_ground_stone");
    public static final TagKey<Block> ORE_RATES_DENSE = register("ore_rates_dense");
    public static final TagKey<Block> ORE_RATES_SINGULAR = register("ore_rates_singular");
    public static final TagKey<Block> ORE_RATES_SPARSE = register("ore_rates_sparse");
    public static final TagKey<Block> ORES_IN_GROUND_DEEPSLATE = register("ores_in_ground_deepslate");
    public static final TagKey<Block> ORES_IN_GROUND_NETHERRACK = register("ores_in_ground_netherrack");
    public static final TagKey<Block> ORES_IN_GROUND_STONE = register("ores_in_ground_stone");
    public static final TagKey<Block> SHULKER_BOXES = register("shulker_boxes");
    public static final TagKey<Block> GLAZED_TERRACOTTA = register("glazed_terracotta");
    public static final TagKey<Block> CONCRETE = register("concrete");
}
