#!/usr/bin/env python3
"""Independent verifier for plan44 G-02 (hardness 1095) + G-03 (mining fields).

Reads minecraft-data blocks.json (+ items.json) and the generated
src/generated/BlockStates.hpp with SELF-CONTAINED logic (no imports from
tools/gen_tables.py or tools/mining_fields.py — sharing only the SOURCE
blocks.json, so generator transcription bugs are still caught; cf. plan44
§2/§4 "independent implementation" rule). Compares all 1095 rows and emits
tests/data/block_mining_expected.inc for the C++ lock test.

Independent conventions (documented, not shared):
  hardness/blast: generator prints %.2f; this script requantizes the vanilla
    value with "%.2f" and compares the STRINGS (exact, no epsilon debates).
    blast barrier/light 3600000.8 needs float32 slack in C++ (eps 0.5 there).
  tool bits: pickaxe=1 axe=2 shovel=4 hoe=8 sword=16 shears=32 (spec order).
  tier: 0 none, 1 wooden+, 2 stone+, 3 iron+, 4 diamond+ (gold == wood).

Usage: BLOCKS_JSON=... ITEMS_JSON=... python3 tools/check_hardness.py
Exit 1 on any mismatch.
"""
import json
import os
import re
import sys

BLOCKS_JSON = os.environ.get("BLOCKS_JSON", "/tmp/opencode/blocks.json")
ITEMS_JSON = os.environ.get("ITEMS_JSON", "/tmp/opencode/items.json")
HERE = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(HERE, "..", "src", "generated", "BlockStates.hpp")
OUT = os.path.join(HERE, "..", "tests", "data", "block_mining_expected.inc")

blocks = json.load(open(BLOCKS_JSON))
item_name = {str(i["id"]): i["name"] for i in json.load(open(ITEMS_JSON))}

PICK, AXE, SHOVEL, HOE, SWORD, SHEARS = 1, 2, 4, 8, 16, 32
TAG2BIT = {"mineable/pickaxe": PICK, "mineable/axe": AXE,
           "mineable/shovel": SHOVEL, "mineable/hoe": HOE}
RANK = {"wooden": 0, "golden": 0, "stone": 1, "iron": 2,
        "diamond": 3, "netherite": 4}


def kind_bit(item):
    if item == "shears":
        return SHEARS
    for suffix, bit in (("_pickaxe", PICK), ("_axe", AXE), ("_shovel", SHOVEL),
                        ("_hoe", HOE), ("_sword", SWORD)):
        if item.endswith(suffix):
            return bit
    return 0


expected = {}
for b in blocks:
    name = "minecraft:" + b["name"]
    parts = set((b.get("material") or "default").split(";"))
    tools = b.get("harvestTools") or {}
    names = [item_name.get(t, item_name.get(int(t), "")) for t in tools]
    base = 0
    for p in parts:
        base |= TAG2BIT.get(p, 0)
    hbits = 0
    for n in names:
        hbits |= kind_bit(n)
    req = (base | hbits) if tools else 0
    eff = base | hbits
    if parts & {"wool", "leaves", "vine_or_glow_lichen", "coweb"}:
        eff |= SHEARS
    if "incorrect_for_wooden_tool" in parts:
        eff |= PICK
    lvls = [RANK[n.split("_")[0]] for n in names
            if not (n == "shears" or n.endswith("_sword")) and n.split("_")[0] in RANK]
    tier = (min(lvls) + 1) if lvls else 0
    expected[name] = ("%.2f" % float(b.get("hardness", -1)),
                      "%.2f" % float(b.get("resistance", 0) or 0),
                      req, eff, tier)

ROW = re.compile(
    r'^\s*\{"(minecraft:[^"]+)", (\d+), (\d+), (\d+), ([0-9.\-]+)f, '
    r'([0-9.\-]+)f, (\d+), (\d+), (\d+), (\d+), (\d+), (?:true|false), (\d+), (\d+)\},$')
found = {}
for line in open(HEADER):
    m = ROW.match(line)
    if m:
        found[m.group(1)] = ("%.2f" % float(m.group(5)), "%.2f" % float(m.group(6)),
                             int(m.group(7)), int(m.group(8)), int(m.group(9)))

bad = 0
missing = set(expected) - set(found)
extra = set(found) - set(expected)
for n in sorted(missing):
    print("MISSING in header: %s" % n)
    bad += 1
for n in sorted(extra):
    print("EXTRA in header: %s" % n)
    bad += 1
for n in sorted(set(expected) & set(found)):
    if expected[n] != found[n]:
        print("MISMATCH %s vanilla=%s header=%s" % (n, expected[n], found[n]))
        bad += 1
        if bad > 15:
            print("... (truncated)")
            break
print("blocks.json=%d header=%d mismatches=%d" % (len(expected), len(found), bad))
if bad:
    sys.exit(1)

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("// GENERATED by tools/check_hardness.py from blocks.json — DO NOT EDIT.\n")
    f.write("// Independent expectation table for test_block_hardness_full (plan44 G-02/G-03).\n")
    f.write("struct ExpectedMining {\n")
    f.write("  const char* name; float hardness; float blast;\n")
    f.write("  unsigned toolMask; unsigned effMask; unsigned needsTier;\n};\n")
    f.write("static const ExpectedMining kExpectedMining[] = {\n")
    for b in blocks:
        n = "minecraft:" + b["name"]
        h, r, req, eff, tier = expected[n]
        f.write('  {"%s", %sf, %sf, %d, %d, %d},\n' % (n, h, r, req, eff, tier))
    f.write("};\n")
    f.write("static constexpr int kExpectedMiningCount = %d;\n" % len(blocks))
print("wrote %s (%d rows)" % (OUT, len(blocks)))
