#!/usr/bin/env python3
"""Pack read-only runtime inputs into a small C++ resource header.

The resulting pack is intentionally a tiny private format rather than a ZIP:
the native executable can extract it without depending on an archive library,
while zlib (already required by the server) keeps the generated object small.
Paths are normalized to forward-slash, relative resource names so the same
header works on Windows, macOS, and Linux.
"""

from __future__ import annotations

import argparse
import struct
import zlib
from pathlib import Path

MAGIC = b"CPPFMRES1"
MAX_FILE_SIZE = 64 * 1024 * 1024
MAX_TOTAL_SIZE = 256 * 1024 * 1024


def collect(root: Path, prefix: str, entries: list[tuple[str, bytes]]) -> None:
    if not root.is_dir():
        return
    paths = (path for path in root.rglob("*")
             if path.is_file() and not path.is_symlink())
    for path in sorted(paths, key=lambda item: item.relative_to(root).as_posix()):
        data = path.read_bytes()
        if len(data) > MAX_FILE_SIZE:
            raise ValueError(f"resource is too large: {path}")
        relative = path.relative_to(root).as_posix()
        name = f"{prefix}/{relative}"
        entries.append((name, data))


def build_pack(entries: list[tuple[str, bytes]]) -> bytes:
    entries.sort(key=lambda item: item[0])
    if len({name for name, _ in entries}) != len(entries):
        raise ValueError("duplicate embedded resource path")
    total = sum(len(data) for _, data in entries)
    if total > MAX_TOTAL_SIZE:
        raise ValueError(f"embedded resources exceed {MAX_TOTAL_SIZE} bytes")

    output = bytearray(MAGIC)
    output.extend(struct.pack("<I", len(entries)))
    for name, data in entries:
        encoded_name = name.encode("utf-8")
        compressed = zlib.compress(data, 9)
        output.extend(struct.pack("<IQQ", len(encoded_name), len(data), len(compressed)))
        output.extend(encoded_name)
        output.extend(compressed)
    return bytes(output)


def render(pack: bytes) -> str:
    values = ",\n".join(
        "    " + ", ".join(f"0x{byte:02x}" for byte in pack[offset:offset + 24])
        for offset in range(0, len(pack), 24)
    )
    return f"""// Generated by tools/embed_runtime.py; do not edit by hand.
#pragma once
#include <cstddef>
#include <cstdint>

namespace cppfm::embedded {{
inline constexpr std::uint8_t kPack[] = {{
{values}
}};
inline constexpr std::size_t kPackSize = sizeof(kPack);
inline constexpr bool kHasPack = true;
}} // namespace cppfm::embedded
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--assets-dir", type=Path, required=True)
    parser.add_argument("--classes-dir", type=Path, required=True)
    parser.add_argument("--compile-stubs-dir", type=Path)
    parser.add_argument("--template", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    entries: list[tuple[str, bytes]] = []
    collect(args.assets_dir, "assets", entries)
    collect(args.classes_dir, ".cppfm/jvm/classes", entries)
    if args.compile_stubs_dir is not None:
        collect(args.compile_stubs_dir, ".cppfm/jvm/compile-stubs", entries)
    if args.template.is_file():
        entries.append(("server.properties.example", args.template.read_bytes()))
    pack = build_pack(entries)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    # Path.write_text(newline=...) is not available on every Python version
    # shipped by older macOS installations.  Path.open has supported the
    # newline argument for much longer and keeps the generated header stable.
    with args.output.open("w", encoding="utf-8", newline="\n") as output:
        output.write(render(pack))
    print(f"embedded resources: {len(entries)} files, {len(pack)} packed bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
