#!/usr/bin/env python3
"""Generate src/generated/ItemIds.hpp from PrismarineJS items.json."""
import json
import os

SRC = os.environ.get("ITEMS_JSON", "/tmp/opencode/ref/items.json")
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "generated", "ItemIds.hpp")

with open(SRC, encoding="utf-8") as source:
    data = json.load(source)
rows = sorted(((("minecraft:" + it["name"]), int(it["id"])) for it in data),
              key=lambda r: r[1])
max_id = rows[-1][1]

def format_rows(rows, width=4):
    """Keep generated initializers readable without one source line per item."""
    rendered = ['{"%s", %d},' % (n, i) for n, i in rows]
    return "\n".join(
        "  " + " ".join(rendered[start:start + width])
        for start in range(0, len(rendered), width)
    )


entries = format_rows(rows)

h = """// GENERATED by tools/gen_items.py -- DO NOT EDIT BY HAND.
#pragma once
#include <array>
#include <cstdint>
#include <string_view>
#include <unordered_map>
#include <utility>

namespace cppfm::gen {

inline constexpr std::array<std::pair<std::string_view, std::uint32_t>, %d> kItems = {{
%s
}};

inline const std::unordered_map<std::string_view, std::uint32_t>& itemIdByName() {
  static const std::unordered_map<std::string_view, std::uint32_t> m = [] {
    std::unordered_map<std::string_view, std::uint32_t> mm;
    mm.reserve(kItems.size());
    for (auto& e : kItems) mm.emplace(e.first, e.second);
    return mm;
  }();
  return m;
}

} // namespace cppfm::gen
""" % (len(rows), entries)

with open(OUT, "w", encoding="utf-8") as output:
    output.write(h)
print("wrote %s (%d items, maxId=%d)" % (OUT, len(rows), max_id))
