#!/usr/bin/env python3
"""Generate src/generated/EntityIds.hpp from PrismarineJS entities.json."""
import json, os

SRC = "/tmp/opencode/ref/entities.json"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "generated", "EntityIds.hpp")

data = json.load(open(SRC))
rows = sorted(((("minecraft:" + e["name"]), int(e["id"])) for e in data),
              key=lambda r: r[1])
entries = "\n".join('  {"%s", %d},' % (n, i) for n, i in rows)

h = """// GENERATED by tools/gen_entities.py -- DO NOT EDIT BY HAND.
#pragma once
#include <array>
#include <cstdint>
#include <string_view>
#include <unordered_map>
#include <utility>

namespace cppfm::gen {

inline constexpr std::uint32_t kPlayerEntityTypeId = %d;

inline constexpr std::array<std::pair<std::string_view, std::uint32_t>, %d> kEntities = {{
%s
}};

inline const std::unordered_map<std::string_view, std::uint32_t>& entityTypeIdByName() {
  static const std::unordered_map<std::string_view, std::uint32_t> m = [] {
    std::unordered_map<std::string_view, std::uint32_t> mm;
    mm.reserve(kEntities.size());
    for (auto& e : kEntities) mm.emplace(e.first, e.second);
    return mm;
  }();
  return m;
}

} // namespace cppfm::gen
""" % (dict(rows).get("minecraft:player", 147), len(rows), entries)

open(OUT, "w").write(h)
print("wrote %s (%d entities)" % (OUT, len(rows)))
