#!/usr/bin/env python3
"""Generate src/generated/BlockStates.hpp from PrismarineJS blocks.json (clean-room data)."""
import json, os

SRC = "/tmp/opencode/ref/blocks.json"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "generated", "BlockStates.hpp")

data = json.load(open(SRC))
rows = []
for b in data:
    name = "minecraft:" + b["name"]
    st = b.get("defaultState")
    if st is None:
        st = b.get("minStateId")
    rows.append((name, int(st)))
rows.sort(key=lambda r: r[1])
max_state = max(r[1] for r in rows)

entries = "\n".join('  {"%s", %d},' % (n, s) for n, s in rows)

h = """// GENERATED by tools/gen_tables.py -- DO NOT EDIT BY HAND.
// Block state id table for protocol 769 (1.21.4).
// Source: community-maintained block state list (PrismarineJS minecraft-data).
#pragma once
#include <array>
#include <cstdint>
#include <string_view>
#include <unordered_map>

namespace cppfm::gen {

inline constexpr std::uint16_t kMaxBlockStateId = %d;

struct BlockEntry { std::string_view name; std::uint32_t state; };

inline constexpr std::array<BlockEntry, %d> kBlocks = {{
%s
}};

// name -> default state id
inline const std::unordered_map<std::string_view, std::uint32_t>& blockNameToState() {
  static const std::unordered_map<std::string_view, std::uint32_t> m = [] {
    std::unordered_map<std::string_view, std::uint32_t> mm;
    mm.reserve(kBlocks.size());
    for (auto& e : kBlocks) mm.emplace(e.name, e.state);
    return mm;
  }();
  return m;
}

} // namespace cppfm::gen
""" % (max_state, len(rows), entries)

open(OUT, "w").write(h)
print("wrote %s: %d blocks, maxState=%d" % (OUT, len(rows), max_state))
