#!/usr/bin/env python3
"""Generate src/generated/ItemIds.hpp from PrismarineJS items.json."""
import json, os

SRC = "/tmp/opencode/ref/items.json"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "generated", "ItemIds.hpp")

data = json.load(open(SRC))
rows = sorted(((("minecraft:" + it["name"]), int(it["id"])) for it in data),
              key=lambda r: r[1])
max_id = rows[-1][1]

entries = "\n".join('  {"%s", %d},' % (n, i) for n, i in rows)

h = """// GENERATED by tools/gen_items.py -- DO NOT EDIT BY HAND.
#pragma once
#include <array>
#include <cstdint>
#include <string_view>
#include <unordered_map>
#include <utility>

namespace cppfm::gen {

inline constexpr std::array<std::pair<std::string_view, std::uint32_t>, %d> kItems = {{
%s
}};

inline const std::unordered_map<std::string_view, std::uint32_t>& itemIdByName() {
  static const std::unordered_map<std::string_view, std::uint32_t> m = [] {
    std::unordered_map<std::string_view, std::uint32_t> mm;
    mm.reserve(kItems.size());
    for (auto& e : kItems) mm.emplace(e.first, e.second);
    return mm;
  }();
  return m;
}

} // namespace cppfm::gen
""" % (len(rows), entries)

open(OUT, "w").write(h)
print("wrote %s (%d items, maxId=%d)" % (OUT, len(rows), max_id))
