# tools/seed_parity_check.py — plan45 G-11 seed parity L1 (self-consistency).
#
# Independent Python implementation of worldgen::smStructureHash /
# triangularOffsetRaw / smStructureAtChunk (StructureManager.hpp). Shares NO
 # code with the C++ generator (G-01 tautology guard): the algorithm is
 # ported by hand from the spec comment, and its outputs are pasted as
 # hardcoded expectations into tests/test_seed_parity.cpp.
#
# Vanilla parity note (L3): vanilla uses Xoroshiro128++/LegacyRand, so this
 # checks SELF-consistency (hash hand-calc == generate() placement) and
 # determinism, NOT vanilla seed equality. See docs/SPEC_GAMEPLAY.md#worldgen-density-and-seed-limits.
#
# Usage: python3 tools/seed_parity_check.py  (prints C++ CHECK lines)
import math

M64 = 0xFFFFFFFFFFFFFFFF


def sm_hash(seed, gx, gz, salt):
    h = (seed ^ salt) & M64
    h ^= ((gx & M64) * 0x9E3779B97F4A7C15) & M64
    h &= M64
    h ^= ((gz & M64) * 0xC2B2AE3D27D4EB4F) & M64
    h &= M64
    h ^= h >> 33
    h = (h * 0xFF51AFD7ED558CCD) & M64
    h ^= h >> 33
    h &= M64
    return (h >> 11) / float(1 << 53)


def tri_raw(seed, gx, gz, salt, rng):
    if rng <= 0:
        return 0
    r1 = sm_hash(seed, gx, gz, salt)
    r2 = sm_hash(seed, gx, gz, salt ^ 0x9E3779B97F4A7C15)
    return (int(r1 * rng) + int(r2 * rng)) // 2


# (name, spacing, separation, salt, triangular?)
SETS = [
    ("village", 34, 8, 10387312, False),
    ("desert_pyramid", 32, 8, 14357617, False),
    ("monument", 32, 5, 10387313, True),
    ("mansion", 80, 20, 10387319, True),
    ("trial_chambers", 34, 12, 94251327, False),
]
SEEDS = [12345, 0, 1378645410614731511]
MAXH = 3


def find_present(sp, se, salt, tri, seed):
    # first chunk (spiral scan) where the set actually places, so L1 locks
    # exact origin coordinates instead of only asserting absence.
    for r in range(0, 200):
        for cx in range(-r, r + 1):
            for cz in (-r, r):
                pr, ox, oz = at_chunk(sp, se, salt, tri, seed, cx, cz)
                if pr:
                    return (cx, cz, ox, oz)
            for cz in range(-r + 1, r):
                for cx in (-r, r):
                    pr, ox, oz = at_chunk(sp, se, salt, tri, seed, cx, cz)
                    if pr:
                        return (cx, cz, ox, oz)
    return (0, 0, 0, 0)


def at_chunk(spacing, separation, salt, tri, seed, cx, cz):
    rng = spacing - separation
    gx = math.floor(cx / spacing)
    gz = math.floor(cz / spacing)
    best = None
    for ox in (-1, 0, 1):
        for oz in (-1, 0, 1):
            cellx, cellz = gx + ox, gz + oz
            if tri:
                offx = tri_raw(seed, cellx, cellz, salt, rng)
                offz = tri_raw(seed, cellx, cellz,
                               salt ^ 0xC2B2AE3D27D4EB4F, rng)
            else:
                offx = int(sm_hash(seed, cellx, cellz, salt) * rng)
                offz = int(sm_hash(seed, cellx, cellz, salt ^ 0x9E37) * rng)
            scx = cellx * spacing + offx
            scz = cellz * spacing + offz
            if not (scx - MAXH <= cx <= scx + MAXH):
                continue
            if not (scz - MAXH <= cz <= scz + MAXH):
                continue
            d = abs(scx - cx) + abs(scz - cz)
            if best is None or d < best[0]:
                best = (d, scx, scz)
    if best is None:
        return (False, 0, 0)
    return (True, best[1], best[2])


def main():
    n = 0
    print("// generated by tools/seed_parity_check.py — DO NOT HAND-EDIT")
    for name, sp, se, salt, tri in SETS:
        for seed in SEEDS:
            qx, qz, ox, oz = find_present(sp, se, salt, tri, seed)
            n += 1
            print(f'    {{ SMStructureSet s; s.name="minecraft:{name}"; '
                  f's.spacing={sp}; s.separation={se}; s.salt={salt}ULL; '
                  f's.spread=SMStructureSet::{"Triangular" if tri else "Linear"}; '
                  f's.maxHoriz=3; auto at=smStructureAtChunk(s,{seed}ULL,{qx},{qz}); '
                  f'CHECK(at.present==true, '
                  f'"L1 {name} seed {seed} present"); '
                  f'CHECK_EQ_INT(at.originCx,{ox}, "L1 {name} seed {seed} ocx"); '
                  f'CHECK_EQ_INT(at.originCz,{oz}, "L1 {name} seed {seed} ocz"); }}')
    # bonus: pillager_outpost frequency gate (jar: 0.2 legacy_type_1)
    for seed in SEEDS:
        r = sm_hash(seed, 0, 0, 165745296 ^ 0xCAFEBABE)
        # placement gate outcome depends on origin; just lock the raw hash
        print(f'    // pillager freq raw seed {seed}: {r:.17g}')
        n += 1
    print(f"// L1 cases: {n} (15 placement + 3 frequency-raw)", flush=True)


if __name__ == "__main__":
    main()
